# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Informatyka_proj_2
                                 A QGIS plugin
 Wtyczka zrobiona jako projekt na informatykę
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-06-09
        copyright            : (C) 2023 by Antoni Kukowski / Rafał Szlendak
        email                : antoni.kukowski.stud@pw.edu.pl
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Informatyka_proj_2 class from file Informatyka_proj_2.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Projekt_2 import Informatyka_proj_2
    return Informatyka_proj_2(iface)
